# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adicionar.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(528, 460)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.label_3 = QtGui.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(50, 250, 111, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayoutWidget = QtGui.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 391, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.nome = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.nome.setObjectName(_fromUtf8("nome"))
        self.horizontalLayout.addWidget(self.nome)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 50, 281, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.album = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.album.setObjectName(_fromUtf8("album"))
        self.horizontalLayout_2.addWidget(self.album)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 91, 191, 30))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.numero = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.numero.setMaximum(1000000)
        self.numero.setProperty("value", 0)
        self.numero.setObjectName(_fromUtf8("numero"))
        self.horizontalLayout_3.addWidget(self.numero)
        self.salvar = QtGui.QPushButton(Frame)
        self.salvar.setGeometry(QtCore.QRect(60, 310, 79, 25))
        self.salvar.setObjectName(_fromUtf8("salvar"))
        self.limpar = QtGui.QPushButton(Frame)
        self.limpar.setGeometry(QtCore.QRect(60, 340, 79, 25))
        self.limpar.setObjectName(_fromUtf8("limpar"))
        self.texto = QtGui.QTextEdit(Frame)
        self.texto.setGeometry(QtCore.QRect(160, 260, 361, 161))
        self.texto.setObjectName(_fromUtf8("texto"))
        self.label_5 = QtGui.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(10, 420, 111, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.linhas = QtGui.QLabel(Frame)
        self.linhas.setGeometry(QtCore.QRect(120, 420, 41, 16))
        self.linhas.setText(_fromUtf8(""))
        self.linhas.setObjectName(_fromUtf8("linhas"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(Frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(60, 120, 301, 30))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.autor = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.autor.setObjectName(_fromUtf8("autor"))
        self.horizontalLayout_4.addWidget(self.autor)
        self.pesquisar = QtGui.QPushButton(Frame)
        self.pesquisar.setGeometry(QtCore.QRect(60, 370, 79, 25))
        self.pesquisar.setObjectName(_fromUtf8("pesquisar"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(Frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(60, 150, 451, 30))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.linkmusica = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.linkmusica.setObjectName(_fromUtf8("linkmusica"))
        self.horizontalLayout_5.addWidget(self.linkmusica)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(Frame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(60, 180, 451, 30))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.linkicone = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.linkicone.setObjectName(_fromUtf8("linkicone"))
        self.horizontalLayout_6.addWidget(self.linkicone)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(Frame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(60, 210, 451, 30))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.linktrecho = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.linktrecho.setObjectName(_fromUtf8("linktrecho"))
        self.horizontalLayout_7.addWidget(self.linktrecho)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.nome, self.album)
        Frame.setTabOrder(self.album, self.numero)
        Frame.setTabOrder(self.numero, self.autor)
        Frame.setTabOrder(self.autor, self.texto)
        Frame.setTabOrder(self.texto, self.salvar)
        Frame.setTabOrder(self.salvar, self.limpar)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Adicionar Texto", None))
        self.label_3.setText(_translate("Frame", "Texto da Musica:", None))
        self.label.setText(_translate("Frame", "Nome:", None))
        self.label_4.setText(_translate("Frame", "Album:", None))
        self.label_2.setText(_translate("Frame", "Numero da faixa:", None))
        self.salvar.setText(_translate("Frame", "Salvar", None))
        self.limpar.setText(_translate("Frame", "Limpar", None))
        self.label_5.setText(_translate("Frame", "Numero de linhas:", None))
        self.label_6.setText(_translate("Frame", "Autor:", None))
        self.pesquisar.setText(_translate("Frame", "Pesquisar", None))
        self.label_7.setText(_translate("Frame", "Link - Musica", None))
        self.label_8.setText(_translate("Frame", "Link - Icone", None))
        self.label_9.setText(_translate("Frame", "Link - trecho", None))

