# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coletaneas.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(541, 985)
        Frame.setMinimumSize(QtCore.QSize(541, 877))
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 230, 503, 226))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btnAdoradores3 = QtWidgets.QPushButton(self.layoutWidget)
        self.btnAdoradores3.setMinimumSize(QtCore.QSize(161, 201))
        self.btnAdoradores3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icones/adoradores 3.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdoradores3.setIcon(icon)
        self.btnAdoradores3.setIconSize(QtCore.QSize(168, 225))
        self.btnAdoradores3.setObjectName("btnAdoradores3")
        self.verticalLayout_11.addWidget(self.btnAdoradores3)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_12.addWidget(self.pushButton_21)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_13.addWidget(self.pushButton_22)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 460, 503, 226))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pushButton_29 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_29.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_20.addWidget(self.pushButton_29)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_20.addWidget(self.label_20, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_30.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_21.addWidget(self.pushButton_30)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_21.addWidget(self.label_21, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.pushButton_31 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_31.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_22.addWidget(self.pushButton_31)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_22.addWidget(self.label_22, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_22)
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 690, 503, 226))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.pushButton_32 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.pushButton_32.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_32.setObjectName("pushButton_32")
        self.verticalLayout_23.addWidget(self.pushButton_32)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.pushButton_33 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.pushButton_33.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout_24.addWidget(self.pushButton_33)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_24.addWidget(self.label_24, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.pushButton_34 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.pushButton_34.setMinimumSize(QtCore.QSize(161, 201))
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout_25.addWidget(self.pushButton_34)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_25.addWidget(self.label_25, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_25)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 503, 226))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnAdoradores = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAdoradores.setMinimumSize(QtCore.QSize(161, 201))
        self.btnAdoradores.setStyleSheet("background-color: rgb(20, 147, 226);")
        self.btnAdoradores.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icones/adoradores 2.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdoradores.setIcon(icon1)
        self.btnAdoradores.setIconSize(QtCore.QSize(162, 226))
        self.btnAdoradores.setCheckable(False)
        self.btnAdoradores.setObjectName("btnAdoradores")
        self.verticalLayout_8.addWidget(self.btnAdoradores)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnDiferente = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnDiferente.setMinimumSize(QtCore.QSize(161, 201))
        self.btnDiferente.setStyleSheet("background-color: rgb(71, 252, 255);")
        self.btnDiferente.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("diferente.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDiferente.setIcon(icon2)
        self.btnDiferente.setIconSize(QtCore.QSize(168, 225))
        self.btnDiferente.setObjectName("btnDiferente")
        self.verticalLayout_9.addWidget(self.btnDiferente)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btnAdoradores2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAdoradores2.setMinimumSize(QtCore.QSize(161, 201))
        self.btnAdoradores2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icones/adoradores1.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdoradores2.setIcon(icon3)
        self.btnAdoradores2.setIconSize(QtCore.QSize(168, 225))
        self.btnAdoradores2.setObjectName("btnAdoradores2")
        self.verticalLayout_10.addWidget(self.btnAdoradores2)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Capas - Coletanea"))
        self.label_11.setText(_translate("Frame", "Adoradores 3"))
        self.pushButton_21.setText(_translate("Frame", "PushButton"))
        self.label_12.setText(_translate("Frame", "Adoradores 1"))
        self.pushButton_22.setText(_translate("Frame", "PushButton"))
        self.label_13.setText(_translate("Frame", "Adoradores 1"))
        self.pushButton_29.setText(_translate("Frame", "PushButton"))
        self.label_20.setText(_translate("Frame", "Adoradores 1"))
        self.pushButton_30.setText(_translate("Frame", "PushButton"))
        self.label_21.setText(_translate("Frame", "Adoradores 1"))
        self.pushButton_31.setText(_translate("Frame", "PushButton"))
        self.label_22.setText(_translate("Frame", "Adoradores 1"))
        self.pushButton_32.setText(_translate("Frame", "PushButton"))
        self.label_23.setText(_translate("Frame", "Adoradores 1"))
        self.pushButton_33.setText(_translate("Frame", "PushButton"))
        self.label_24.setText(_translate("Frame", "Adoradores 1"))
        self.pushButton_34.setText(_translate("Frame", "PushButton"))
        self.label_25.setText(_translate("Frame", "Adoradores 1"))
        self.label_8.setText(_translate("Frame", "Adoradores 2"))
        self.label_9.setText(_translate("Frame", "Diferente"))
        self.label_10.setText(_translate("Frame", "Adoradores 1"))

