# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sono7.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(822, 465)
        self.area_trecho = QtWidgets.QSplitter(Form)
        self.area_trecho.setGeometry(QtCore.QRect(271, 9, 256, 215))
        self.area_trecho.setMaximumSize(QtCore.QSize(256, 16777215))
        self.area_trecho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.area_trecho.setOrientation(QtCore.Qt.Vertical)
        self.area_trecho.setObjectName("area_trecho")
        self.label_3 = QtWidgets.QLabel(self.area_trecho)
        self.label_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lista_trechos = QtWidgets.QListWidget(self.area_trecho)
        self.lista_trechos.setMaximumSize(QtCore.QSize(256, 184))
        self.lista_trechos.setObjectName("lista_trechos")
        self.area_playlist = QtWidgets.QSplitter(Form)
        self.area_playlist.setGeometry(QtCore.QRect(9, 9, 256, 215))
        self.area_playlist.setMaximumSize(QtCore.QSize(256, 16777215))
        self.area_playlist.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.area_playlist.setOrientation(QtCore.Qt.Vertical)
        self.area_playlist.setObjectName("area_playlist")
        self.label_4 = QtWidgets.QLabel(self.area_playlist)
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lista_playlist = QtWidgets.QListWidget(self.area_playlist)
        self.lista_playlist.setMaximumSize(QtCore.QSize(256, 187))
        self.lista_playlist.setObjectName("lista_playlist")
        self.adicionar_midia = QtWidgets.QToolButton(self.area_playlist)
        self.adicionar_midia.setObjectName("adicionar_midia")
        self.area_busca_album = QtWidgets.QSplitter(Form)
        self.area_busca_album.setGeometry(QtCore.QRect(530, 10, 266, 453))
        self.area_busca_album.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.area_busca_album.setOrientation(QtCore.Qt.Vertical)
        self.area_busca_album.setObjectName("area_busca_album")
        self.area_buscar = QtWidgets.QSplitter(self.area_busca_album)
        self.area_buscar.setMaximumSize(QtCore.QSize(266, 16777215))
        self.area_buscar.setOrientation(QtCore.Qt.Vertical)
        self.area_buscar.setObjectName("area_buscar")
        self.label = QtWidgets.QLabel(self.area_buscar)
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.splitter = QtWidgets.QSplitter(self.area_buscar)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.buscar_area = QtWidgets.QLineEdit(self.splitter)
        self.buscar_area.setStyleSheet("border-color: rgb(188, 188, 188);")
        self.buscar_area.setObjectName("buscar_area")
        self.botao_buscar = QtWidgets.QPushButton(self.splitter)
        self.botao_buscar.setMaximumSize(QtCore.QSize(75, 23))
        self.botao_buscar.setObjectName("botao_buscar")
        self.caixa_opcao = QtWidgets.QComboBox(self.splitter)
        self.caixa_opcao.setMaximumSize(QtCore.QSize(58, 23))
        self.caixa_opcao.setObjectName("caixa_opcao")
        self.caixa_opcao.addItem("")
        self.caixa_opcao.addItem("")
        self.caixa_opcao.addItem("")
        self.lista_busca = QtWidgets.QListWidget(self.area_buscar)
        self.lista_busca.setMaximumSize(QtCore.QSize(266, 155))
        self.lista_busca.setObjectName("lista_busca")
        self.area_album = QtWidgets.QSplitter(self.area_busca_album)
        self.area_album.setEnabled(True)
        self.area_album.setOrientation(QtCore.Qt.Vertical)
        self.area_album.setObjectName("area_album")
        self.label_9 = QtWidgets.QLabel(self.area_album)
        self.label_9.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.lista_album = QtWidgets.QListWidget(self.area_album)
        self.lista_album.setObjectName("lista_album")
        self.area_controles = QtWidgets.QSplitter(Form)
        self.area_controles.setGeometry(QtCore.QRect(10, 240, 75, 69))
        self.area_controles.setOrientation(QtCore.Qt.Vertical)
        self.area_controles.setObjectName("area_controles")
        self.play = QtWidgets.QPushButton(self.area_controles)
        self.play.setMaximumSize(QtCore.QSize(75, 21))
        self.play.setObjectName("play")
        self.audio = QtWidgets.QPushButton(self.area_controles)
        self.audio.setMinimumSize(QtCore.QSize(75, 20))
        self.audio.setMaximumSize(QtCore.QSize(75, 20))
        self.audio.setObjectName("audio")
        self.stop = QtWidgets.QPushButton(self.area_controles)
        self.stop.setObjectName("stop")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.buscar_area, self.lista_playlist)
        Form.setTabOrder(self.lista_playlist, self.adicionar_midia)
        Form.setTabOrder(self.adicionar_midia, self.play)
        Form.setTabOrder(self.play, self.audio)
        Form.setTabOrder(self.audio, self.stop)
        Form.setTabOrder(self.stop, self.lista_busca)
        Form.setTabOrder(self.lista_busca, self.lista_album)
        Form.setTabOrder(self.lista_album, self.lista_trechos)
        Form.setTabOrder(self.lista_trechos, self.botao_buscar)
        Form.setTabOrder(self.botao_buscar, self.caixa_opcao)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sono7"))
        self.label_3.setText(_translate("Form", "Trechos:"))
        self.label_4.setText(_translate("Form", "PlayList Automatica:"))
        self.adicionar_midia.setText(_translate("Form", "Adicionar Midia Externa"))
        self.label.setText(_translate("Form", "Buscar:"))
        self.botao_buscar.setText(_translate("Form", "Buscar"))
        self.caixa_opcao.setItemText(0, _translate("Form", "Musica"))
        self.caixa_opcao.setItemText(1, _translate("Form", "Album"))
        self.caixa_opcao.setItemText(2, _translate("Form", "Tudo"))
        self.label_9.setText(_translate("Form", "Album:"))
        self.play.setText(_translate("Form", "Play / Pause"))
        self.audio.setText(_translate("Form", "tracker"))
        self.stop.setText(_translate("Form", "Stop"))

