# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface01.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(786, 571)
        MainWindow.setMinimumSize(QtCore.QSize(771, 310))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1451, 331))
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(214, 214, 214);"))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.iconeMusica = QtGui.QLabel(self.tab)
        self.iconeMusica.setGeometry(QtCore.QRect(10, 30, 81, 81))
        self.iconeMusica.setText(_fromUtf8(""))
        self.iconeMusica.setPixmap(QtGui.QPixmap(_fromUtf8("logoAdv.png")))
        self.iconeMusica.setScaledContents(True)
        self.iconeMusica.setObjectName(_fromUtf8("iconeMusica"))
        self.play = QtGui.QPushButton(self.tab)
        self.play.setEnabled(False)
        self.play.setGeometry(QtCore.QRect(110, 30, 101, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("botao-de-play-pause_318-43701.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon)
        self.play.setCheckable(True)
        self.play.setChecked(False)
        self.play.setObjectName(_fromUtf8("play"))
        self.stop = QtGui.QPushButton(self.tab)
        self.stop.setEnabled(False)
        self.stop.setGeometry(QtCore.QRect(110, 60, 101, 23))
        self.stop.setObjectName(_fromUtf8("stop"))
        self.mudarTrack = QtGui.QPushButton(self.tab)
        self.mudarTrack.setEnabled(False)
        self.mudarTrack.setGeometry(QtCore.QRect(110, 90, 101, 25))
        self.mudarTrack.setStyleSheet(_fromUtf8(""))
        self.mudarTrack.setIconSize(QtCore.QSize(30, 16))
        self.mudarTrack.setCheckable(True)
        self.mudarTrack.setObjectName(_fromUtf8("mudarTrack"))
        self.verticalSlider = QtGui.QSlider(self.tab)
        self.verticalSlider.setGeometry(QtCore.QRect(220, 30, 20, 81))
        self.verticalSlider.setStyleSheet(_fromUtf8("background-color: rgb(84, 255, 147);"))
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setProperty("value", 100)
        self.verticalSlider.setSliderPosition(100)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.reproduzindo = QtGui.QLabel(self.tab)
        self.reproduzindo.setGeometry(QtCore.QRect(10, 0, 251, 21))
        self.reproduzindo.setStyleSheet(_fromUtf8("font: 75 italic 12pt \"Sans Serif\";"))
        self.reproduzindo.setObjectName(_fromUtf8("reproduzindo"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 120, 251, 171))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.adicionar = QtGui.QToolButton(self.gridLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("botao-de-play_318-40670.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adicionar.setIcon(icon1)
        self.adicionar.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.adicionar.setObjectName(_fromUtf8("adicionar"))
        self.gridLayout.addWidget(self.adicionar, 1, 1, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.lista_musicas = QtGui.QListWidget(self.gridLayoutWidget)
        self.lista_musicas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lista_musicas.setAcceptDrops(True)
        self.lista_musicas.setToolTip(_fromUtf8(""))
        self.lista_musicas.setStatusTip(_fromUtf8(""))
        self.lista_musicas.setWhatsThis(_fromUtf8(""))
        self.lista_musicas.setAccessibleName(_fromUtf8(""))
        self.lista_musicas.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lista_musicas.setViewMode(QtGui.QListView.ListMode)
        self.lista_musicas.setModelColumn(0)
        self.lista_musicas.setUniformItemSizes(True)
        self.lista_musicas.setObjectName(_fromUtf8("lista_musicas"))
        self.gridLayout.addWidget(self.lista_musicas, 2, 0, 1, 4)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(260, 0, 501, 291))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.trechos3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.trechos3.setStyleSheet(_fromUtf8("font: 75 14pt \"Sans Serif\";"))
        self.trechos3.setObjectName(_fromUtf8("trechos3"))
        self.verticalLayout_2.addWidget(self.trechos3, QtCore.Qt.AlignHCenter)
        self.lista_trecho = QtGui.QListWidget(self.horizontalLayoutWidget_3)
        self.lista_trecho.setStyleSheet(_fromUtf8("background-color: rgb(252, 252, 252);"))
        self.lista_trecho.setObjectName(_fromUtf8("lista_trecho"))
        self.verticalLayout_2.addWidget(self.lista_trecho)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setStyleSheet(_fromUtf8("font: 75 14pt \"Sans Serif\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pesquisa = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.pesquisa.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pesquisa.setObjectName(_fromUtf8("pesquisa"))
        self.horizontalLayout.addWidget(self.pesquisa)
        self.botaopesquisa = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.botaopesquisa.setObjectName(_fromUtf8("botaopesquisa"))
        self.horizontalLayout.addWidget(self.botaopesquisa)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.nomep = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.nomep.setChecked(True)
        self.nomep.setObjectName(_fromUtf8("nomep"))
        self.horizontalLayout_2.addWidget(self.nomep)
        self.Profissao = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.Profissao.setObjectName(_fromUtf8("Profissao"))
        self.horizontalLayout_2.addWidget(self.Profissao)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listadevalores = QtGui.QListWidget(self.horizontalLayoutWidget_3)
        self.listadevalores.setStyleSheet(_fromUtf8("font: 75 italic 9pt \"Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Sans Serif\";"))
        self.listadevalores.setObjectName(_fromUtf8("listadevalores"))
        self.verticalLayout.addWidget(self.listadevalores)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 340, 771, 211))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setStyleSheet(_fromUtf8("font: 75 12pt \"Sans Serif\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pesquisarAlbum = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.pesquisarAlbum.setObjectName(_fromUtf8("pesquisarAlbum"))
        self.horizontalLayout_3.addWidget(self.pesquisarAlbum)
        self.botaoAlbum = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.botaoAlbum.setObjectName(_fromUtf8("botaoAlbum"))
        self.horizontalLayout_3.addWidget(self.botaoAlbum)
        self.imagem = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.imagem.setObjectName(_fromUtf8("imagem"))
        self.horizontalLayout_3.addWidget(self.imagem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.album = QtGui.QListWidget(self.horizontalLayoutWidget_2)
        self.album.setObjectName(_fromUtf8("album"))
        self.verticalLayout_3.addWidget(self.album)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.conteudoAlbum = QtGui.QListWidget(self.horizontalLayoutWidget_2)
        self.conteudoAlbum.setObjectName(_fromUtf8("conteudoAlbum"))
        self.horizontalLayout_4.addWidget(self.conteudoAlbum)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.iconeMusica.setBuddy(self.mudarTrack)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sono7", None))
        self.play.setText(_translate("MainWindow", "Play - Pause", None))
        self.stop.setText(_translate("MainWindow", "Stop", None))
        self.mudarTrack.setText(_translate("MainWindow", "Playback / Trilha", None))
        self.reproduzindo.setText(_translate("MainWindow", "Sem Midia", None))
        self.label_2.setText(_translate("MainWindow", "Informe a midia externa..", None))
        self.adicionar.setText(_translate("MainWindow", "...", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.trechos3.setText(_translate("MainWindow", "Trechos", None))
        self.label_3.setText(_translate("MainWindow", "Pesquisa", None))
        self.botaopesquisa.setText(_translate("MainWindow", "Go", None))
        self.nomep.setText(_translate("MainWindow", "Nome ou Album", None))
        self.Profissao.setText(_translate("MainWindow", "Trecho", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Midia", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Utilidade", None))
        self.label.setText(_translate("MainWindow", "Albuns", None))
        self.botaoAlbum.setText(_translate("MainWindow", "Go", None))
        self.imagem.setText(_translate("MainWindow", "Capa", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

